### ISSUE TITLE
Detecting when a laptop starts charging

### ISSUE THREAD

**Issue by alba4k** [REALERvolker1/volbright#3]

**Comment by REALERvolker1** [comment]
You might be looking for https://github.com/REALERvolker1/pmgmt-sh. Is this helpful?

**Comment by alba4k** [comment]
yes it is :)

**Comment by REALERvolker1** [comment]
Awesome, glad it helped you

**Comment by alba4k** [comment]
Well actually not really, but it can do the job with some work

I meant something that just sends a notification ( like volbright does for brightness changes)

**Comment by REALERvolker1** [comment]
oh, you can make it send the notification by adding the following to the ac_command_center script before the if statement: `notify-send 'pmgmt' "$ac_state"`. Please open an issue on that page if you want to continue discussion.
